function escTeam(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m];});}
function teamActivity(key){return t("activity."+({padel:"padel",futbol:"futbol",baloncesto:"baloncesto",tenis:"tenis",ajedrez:"ajedrez",gaming:"gaming",running:"running",otro:"other"}[key]||"other"));}
function teamDate(d,time){if(!d)return"";return localeDate(new Date(d+"T"+(time||"00:00")),{day:"numeric",month:"long",year:"numeric"});}
function teamStatus(s){return s==="live"?t("status.live"):s==="finished"?t("status.finished"):s==="preparing"?t("status.preparing"):t("status.upcoming");}
document.addEventListener("DOMContentLoaded",async function(){
  await window.curruscosI18n?.ready;
  var root=document.getElementById("teamRoot"),id=new URLSearchParams(location.search).get("id");
  if(!id){root.innerHTML=escTeam(t("team.notFound"));return;}
  var team=await getPublicTeam(id),persistent=false,events=[];
  if(!team){var result=await supabaseClient.rpc("get_public_persistent_team",{target_team_id:id});if(!result.error&&result.data&&result.data.length){team=result.data[0];persistent=true;events=await getPublicPersistentTeamEvents(id);}}
  if(!team){root.innerHTML=escTeam(t("team.notAvailable"));return;}
  var currentUser=await getCurrentUser(),followStatus=persistent?await getTeamFollowStatus(id):null,members=[];
  if(persistent)members=await getPersistentTeamMembers(id);else{var publicMembers=await getPublicEventTeamMembers(team.event_id);members=(publicMembers||[]).filter(function(member){return member.team_id===id;}).map(function(member){return{user_id:member.user_id,display_name:member.display_name,username:member.username,role:"member"};});}
  var memberHtml=(members||[]).map(function(member){var name=member.display_name||member.username||t("common.participant");return '<a class="team-member" href="perfil-publico.html?id='+encodeURIComponent(member.user_id)+'"><span class="team-avatar">'+escTeam(name.charAt(0).toUpperCase())+'</span><span><strong>'+escTeam(name)+'</strong><small>'+(member.role==="owner"?t("team.owner")+" · ":"")+(member.username?"@"+escTeam(member.username):t("common.viewProfile"))+'</small></span></a>';}).join("");
  if(!memberHtml)memberHtml='<div class="team-empty">'+escTeam(t("team.noVisibleMembers"))+'</div>';
  var eventRows=(events||[]).map(function(event){return '<a class="team-event" href="evento-publico.html?id='+encodeURIComponent(event.event_id)+'"><span><strong>'+escTeam(event.title)+'</strong><small>'+escTeam(teamActivity(event.event_type))+(event.location?" · "+escTeam(event.location):"")+'</small></span><small>'+escTeam(teamDate(event.event_date,event.event_time))+'</small></a>';}).join("");
  if(!eventRows)eventRows='<div class="team-empty">'+escTeam(t("team.noPublicEvents"))+'</div>';
  var eventContext="";
  if(!persistent){eventContext='<section class="team-section"><span class="eyebrow">'+escTeam(t("team.context"))+'</span><h2>'+escTeam(t("event.event"))+'</h2><a class="team-event" href="evento-publico.html?id='+encodeURIComponent(team.event_id)+'"><span><strong>'+escTeam(team.event_title||t("event.event"))+'</strong><small>'+escTeam(teamActivity(team.event_type))+'</small></span><small>'+escTeam(teamDate(team.event_date,null))+'</small></a></section>';}
  var title=persistent?team.name:team.team_name,activity=persistent?t("team.persistent"):teamActivity(team.event_type)+" · "+t("team.team");
  var stats=persistent?[[t("team.members"),team.member_count],[t("event.events"),team.event_count],[t("team.matches"),team.matches_played],[t("team.wins"),team.wins],[t("team.points"),team.points],[t("team.followers"),followStatus&&followStatus.follower_count||0]]:[[t("team.members"),team.member_count],[t("team.matches"),team.matches_played],[t("team.wins"),team.wins],[t("team.losses"),team.losses],[t("team.points"),team.points]];
  var statsHtml=stats.map(function(item){return'<div class="team-stat"><span>'+escTeam(item[0])+'</span><strong>'+Number(item[1]||0)+'</strong></div>';}).join("");
  root.innerHTML='<section class="team-card"><div class="team-head"><div><span class="team-kicker">'+escTeam(activity)+'</span><h1>'+escTeam(title)+'</h1><p>'+(persistent?escTeam(t("team.persistent")):'<a class="team-back" href="evento-publico.html?id='+encodeURIComponent(team.event_id)+'">'+escTeam(team.event_title||t("team.team"))+'</a>')+'</p></div>'+(persistent?"":'<div><span class="team-kicker">'+escTeam(teamStatus(team.event_status||team.status))+'</span></div>')+'</div><div class="team-record">'+statsHtml+'</div></section><div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap"><button id="teamFollowButton" class="button button-primary" type="button">'+(persistent&&currentUser&&currentUser.id!==team.owner_id?(followStatus&&followStatus.is_following?t("team.unfollow"):t("team.follow")):"")+'</button><a class="button button-primary" href="chat.html?team='+encodeURIComponent(id)+'">'+escTeam(t("nav.chat"))+'</a></div><section class="team-section"><span class="eyebrow">'+escTeam(t("team.squad"))+'</span><h2>'+escTeam(t("team.members"))+'</h2><div class="team-members">'+memberHtml+'</div></section><section class="team-section"><span class="eyebrow">'+escTeam(t("team.history"))+'</span><h2>'+escTeam(t("event.events"))+'</h2><div>'+eventRows+'</div></section>'+eventContext;
  var followButton=document.getElementById("teamFollowButton");
  if(followButton&&persistent&&currentUser&&currentUser.id!==team.owner_id){followButton.addEventListener("click",async function(){followButton.disabled=true;var following=followButton.textContent.trim()===t("team.unfollow");var ok=following?await unfollowTeam(id):await followTeam(id);if(ok){followButton.textContent=following?t("team.follow"):t("team.unfollow");var next=await getTeamFollowStatus(id),stat=document.querySelectorAll(".team-stat strong");if(stat.length)stat[stat.length-1].textContent=Number(next&&next.follower_count||0);}followButton.disabled=false;});}else if(followButton)followButton.style.display="none";
});