function escTeam(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
const ACT={padel:"Pádel",futbol:"Fútbol",baloncesto:"Baloncesto",tenis:"Tenis",ajedrez:"Ajedrez",gaming:"Gaming",running:"Running",otro:"Otro"};
document.addEventListener("DOMContentLoaded",async()=>{
 const root=document.getElementById("teamRoot"),id=new URLSearchParams(location.search).get("id");
 if(!id){root.innerHTML="Equipo no encontrado.";return;}
 const team=await getPublicTeam(id);
 if(!team){root.innerHTML="Este equipo no está disponible públicamente.";return;}
 const members=await getPersistentTeamMembers(id);
 const profiles=members||[];
 const memberHtml=profiles.length?profiles.map(p=>`<a class="team-member" href="perfil-publico.html?id=${encodeURIComponent(p.id)}"><span class="team-avatar">${escTeam((p.display_name||p.username||"P").charAt(0).toUpperCase())}</span><span><strong>${escTeam(p.display_name||p.username||"Participante")}</strong><small>${p.role==="owner"?"Propietario · ":""}${p.username?"@"+escTeam(p.username):"Ver perfil"}</small></span></a>`).join(""):"<div class=\"team-empty\">Todavía no hay miembros públicos.</div>";
 root.innerHTML=`<section class="team-card"><div class="team-head"><div><span class="team-kicker">${escTeam(ACT[team.event_type]||"Actividad")} · Equipo</span><h1>${escTeam(team.team_name)}</h1><p><a class="team-back" href="evento-publico.html?id=${encodeURIComponent(team.event_id)}">${escTeam(team.event_title)}</a></p></div><div><span class="team-kicker">${team.event_status==="live"?"En directo":team.event_status==="finished"?"Finalizado":"Próximo"}</span></div></div><div class="team-record"><div class="team-stat"><span>Miembros</span><strong>${Number(team.member_count||0)}</strong></div><div class="team-stat"><span>Partidos</span><strong>${Number(team.matches_played||0)}</strong></div><div class="team-stat"><span>Victorias</span><strong>${Number(team.wins||0)}</strong></div><div class="team-stat"><span>Derrotas</span><strong>${Number(team.losses||0)}</strong></div><div class="team-stat"><span>Puntos</span><strong>${Number(team.points||0)}</strong></div></div></section><div style="margin-top:12px"><a class="button button-primary" href="chat.html?team=${encodeURIComponent(id)}">💬 Chat del equipo</a></div><section class="team-section"><span class="eyebrow">PLANTILLA</span><h2>Miembros</h2><div class="team-members">${memberHtml}</div></section><section class="team-section"><span class="eyebrow">CONTEXTO</span><h2>Evento</h2><a class="team-event" href="evento-publico.html?id=${encodeURIComponent(team.event_id)}"><span><strong>${escTeam(team.event_title)}</strong><small>${escTeam(ACT[team.event_type]||"Actividad")}</small></span><small>${team.event_date?new Date(team.event_date+"T00:00").toLocaleDateString("es-ES",{day:"numeric",month:"long",year:"numeric"}):""}</small></a></section>`;
});
