function escapeHtml(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
const ACTIVITY_LABELS={padel:"Pádel",futbol:"Fútbol",baloncesto:"Baloncesto",tenis:"Tenis",ajedrez:"Ajedrez",gaming:"Gaming",running:"Running",otro:"Otro"};
const CATEGORY_LABELS={tournament:"Torneo",sport:"Deporte",gaming:"Gaming",social:"Social",activity:"Actividad",other:"Otro"};
function eventTimestamp(event){const d=new Date(event.date+"T"+(event.time||"23:59"));return Number.isNaN(d.getTime())?Number.MAX_SAFE_INTEGER:d.getTime();}\nfunction createdTimestamp(event){const d=new Date(event.created_at||0);return Number.isNaN(d.getTime())?0:d.getTime();}\nfunction registrationText(event){if(!event.registration_deadline)return "";const d=new Date(event.registration_deadline);if(Number.isNaN(d.getTime()))return "";if(d.getTime()<Date.now())return "Inscripciones cerradas";return "Hasta "+d.toLocaleDateString("es-ES",{day:"numeric",month:"short"});}
function publicEventDate(event){const d=new Date(event.date+"T"+(event.time||"00:00"));return Number.isNaN(d.getTime())?"Fecha por definir":d.toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"long"});}
function participantCount(event){return Number(event.event_participants?.[0]?.count??0);}
function capacityInfo(event){const count=participantCount(event);if(!event.capacity)return{count,text:count+" inscrito"+(count===1?"":"s"),state:"open"};const remaining=Math.max(Number(event.capacity)-count,0);if(remaining===0)return{count,text:"Sin plazas",state:"full"};return{count,text:remaining+" plaza"+(remaining===1?"":"s")+" libre"+(remaining===1?"":"s"),state:"open"};}
function statusLabel(event){if(event.status==="live")return"En directo";if(event.status==="preparing")return"Preparando";if(event.status==="cancelled")return"Cancelado";if(event.status==="finished")return"Finalizado";return"Inscripciones abiertas";}
function formatLabel(event){return({knockout:"Eliminación",round_robin:"Liga",swiss:"Suizo",race:"Carrera",custom:"Personalizado"}[event.format]||"Evento");}
function cardHtml(event,featured=false){const fee=Number(event.entry_fee||0),info=capacityInfo(event),deadline=registrationText(event),category=ACTIVITY_LABELS[event.event_type]||CATEGORY_LABELS[event.category]||"Evento",organizer=event.organizer_name?" · "+escapeHtml(event.organizer_name):"",format=event.format&&event.format!=="standard"?" · "+formatLabel(event):"";return '<a class="public-event-card'+(featured?" featured":"")+'" href="evento-publico.html?id='+encodeURIComponent(event.id)+'"><span class="public-event-category">'+escapeHtml(category+format)+'</span><span class="public-event-date">'+escapeHtml(publicEventDate(event))+'</span><h2>'+escapeHtml(event.title)+'</h2><div class="public-event-meta">'+escapeHtml(event.location||"Lugar por definir")+'</div><p class="public-event-description">'+escapeHtml(event.description||"Sin descripción todavía.")+'</p><div class="public-event-organizer">Organiza'+(organizer||" · Comunidad Curruscos")+'</div><div class="public-event-bottom"><span class="public-event-price">'+(fee>0?fee.toFixed(2).replace(".",",")+" €":"Gratis")+'</span><span class="public-event-spots">'+escapeHtml(info.text)+'</span><span class="public-event-status '+(info.state==="full"?"full":event.status==="live"?"live":"open")+'">'+escapeHtml(statusLabel(event))+'</span></div></a>';}
function matchesQuickFilter(event,filter){const info=capacityInfo(event);if(filter==="open")return info.state==="open"&&event.status!=="finished"&&event.status!=="cancelled";if(filter==="live")return event.status==="live";if(filter==="soon")return event.status!=="finished"&&event.status!=="cancelled";return true;}
function renderCards(root,events,featured=false){root.innerHTML="";if(!events.length){root.innerHTML='<div class="explore-empty"><strong>No hemos encontrado eventos.</strong><br>Prueba otra búsqueda o cambia los filtros.</div>';return;}root.innerHTML=events.map(e=>cardHtml(e,featured)).join("");}
let currentEvents=[];
function applyAndRender(){const quick=document.querySelector(".explore-chip.active")?.dataset.filter||"all",sort=document.getElementById("eventSort")?.value||"date";let events=currentEvents.filter(e=>matchesQuickFilter(e,quick));events.sort((a,b)=>sort==="newest"?createdTimestamp(b)-createdTimestamp(a):sort==="capacity"?participantCount(b)-participantCount(a):eventTimestamp(a)-eventTimestamp(b));const featured=events.filter(e=>e.status!=="finished"&&e.status!=="cancelled").slice().sort((a,b)=>{const score=e=>participantCount(e)*1000000000-Math.abs(eventTimestamp(e)-Date.now());return score(b)-score(a);}).slice(0,3);renderCards(document.getElementById("featuredEventsGrid"),featured,true);renderCards(document.getElementById("publicEventsGrid"),events.filter(e=>!featured.some(f=>f.id===e.id)));document.getElementById("exploreSummary").textContent=events.length+" evento"+(events.length===1?"":"s")+" disponible"+(events.length===1?"":"s");document.getElementById("allEventsLabel").textContent=events.length?events.length+" resultados":"Sin resultados";document.getElementById("featuredSection").style.display=featured.length?"block":"none";}
async function loadPublicEvents(){currentEvents=await getPublicEvents({search:document.getElementById("eventSearch").value,category:document.getElementById("eventCategory").value,event_type:document.getElementById("eventType").value});applyAndRender();}
document.addEventListener("DOMContentLoaded",async()=>{["eventSearch","eventCategory","eventType","eventSort"].forEach(id=>{const element=document.getElementById(id);element?.addEventListener(id==="eventSearch"?"input":"change",loadPublicEvents);});document.querySelectorAll(".explore-chip").forEach(chip=>chip.addEventListener("click",()=>{document.querySelectorAll(".explore-chip").forEach(c=>c.classList.remove("active"));chip.classList.add("active");applyAndRender();}));await loadPublicEvents();});