/* =========================================================
   CURRUSCOS — INTERNATIONALIZATION
   ========================================================= */

const I18N_SUPPORTED_LANGUAGES = {
  es:{label:"Español",native:"Español",dir:"ltr"},
  en:{label:"English",native:"English",dir:"ltr"},
  fr:{label:"Français",native:"Français",dir:"ltr"},
  de:{label:"Deutsch",native:"Deutsch",dir:"ltr"},
  it:{label:"Italiano",native:"Italiano",dir:"ltr"},
  pt:{label:"Português",native:"Português",dir:"ltr"},
  zh:{label:"中文",native:"中文",dir:"ltr"},
  ar:{label:"العربية",native:"العربية",dir:"rtl"}
};
const I18N_STORAGE_KEY="curruscos_language";
const I18N_DEFAULT_LANGUAGE="es";
const I18N_CACHE={};
function normalizeLanguage(value){const raw=String(value||"").toLowerCase().replace("_","-");const base=raw.split("-")[0];return I18N_SUPPORTED_LANGUAGES[base]?base:null;}
function detectBrowserLanguage(){const candidates=Array.isArray(navigator.languages)?navigator.languages:[navigator.language];for(const candidate of candidates){const normalized=normalizeLanguage(candidate);if(normalized)return normalized;}return I18N_DEFAULT_LANGUAGE;}
function getLanguage(){const stored=normalizeLanguage(localStorage.getItem(I18N_STORAGE_KEY));return stored||detectBrowserLanguage();}
function getNestedValue(source,path){return String(path||"").split(".").reduce((v,k)=>v==null?undefined:v[k],source);}
function interpolate(value,vars){return String(value==null?"":value).replace(/\{\{\s*([\w.-]+)\s*\}\}/g,(_,key)=>Object.prototype.hasOwnProperty.call(vars||{},key)?String(vars[key]):"");}
async function loadLocale(language){const lang=normalizeLanguage(language)||I18N_DEFAULT_LANGUAGE;if(!I18N_CACHE[lang]){I18N_CACHE[lang]=fetch("locales/"+lang+".json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Locale HTTP "+r.status);return r.json();}).catch(error=>{console.warn("No se pudo cargar el idioma",lang,error);return lang!==I18N_DEFAULT_LANGUAGE?loadLocale(I18N_DEFAULT_LANGUAGE):{};});}return I18N_CACHE[lang];}
function t(key,vars={}){const value=getNestedValue(window.curruscosTranslations||{},key);return interpolate(value==null?key:value,vars);}
function localeDate(value,options={}){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?"":new Intl.DateTimeFormat(getLanguage(),options).format(date);}
function localeNumber(value,options={}){return new Intl.NumberFormat(getLanguage(),options).format(Number(value||0));}
function localeCurrency(value,currency="EUR"){return new Intl.NumberFormat(getLanguage(),{style:"currency",currency}).format(Number(value||0));}
const LEGACY_TEXT_KEYS={
  "Explorar":"nav.explore","Mis eventos":"nav.myEvents","Rankings":"nav.rankings","Crear":"nav.create","Entrar":"nav.login","Guardados":"nav.saved","Viajes":"nav.trips","Inicio":"nav.home","Miembros":"nav.members","Historia":"nav.history","Recuerdos":"nav.memories","Eventos":"nav.events","Chat":"nav.chat","Avisos":"nav.notifications","Personas activas":"community.activePeople","Explorar eventos":"landing.exploreEvents","Todas las actividades":"explore.allActivities",
  "Pádel":"activity.padel","Fútbol":"activity.futbol","Baloncesto":"activity.baloncesto","Tenis":"activity.tenis","Ajedrez":"activity.ajedrez","Gaming":"activity.gaming","Running":"activity.running","Otro":"activity.other","Otros":"activity.otherPlural","Torneo":"category.tournament","Deporte":"category.sport","Social":"category.social","Actividad":"category.activity",
  "Cargando…":"common.loading","Cargando...":"common.loading","Buscando...":"common.searching","Guardar":"common.save","Guardado":"common.saved","Cancelar":"common.cancel","Enviar":"common.send","Cerrar":"common.close","Añadir":"common.add","Crear":"common.create","Eliminar":"common.delete","Editar":"common.edit","Ver perfil":"common.viewProfile","Privado":"common.private","Participante":"common.participant","Cargando grupo...":"common.loadingGroup",
  "Seguir equipo":"team.follow","Dejar de seguir":"team.unfollow","Ver equipo →":"team.viewTeam","Propietario":"team.owner","Equipo":"team.team","Equipo persistente":"team.persistent","Plantilla":"team.squad","Historial":"team.history","No hay miembros visibles.":"team.noVisibleMembers","Aún no hay participaciones públicas del equipo.":"team.noPublicEvents","Equipo no encontrado.":"team.notFound","Este equipo no está disponible públicamente.":"team.notAvailable",
  "Inscripciones cerradas":"event.registrationClosed","Sin plazas":"event.noSpots","Gratis":"event.free","Lugar por definir":"event.locationTbd","Sin descripción todavía.":"event.descriptionTbd","Organiza":"event.organizes","Evento":"event.event","Contexto":"event.context","Eventos":"event.events",
  "No hemos encontrado eventos.":"explore.noEvents","Prueba otra búsqueda o cambia los filtros.":"explore.tryFilters","No me interesa":"explore.notInterested","Filtros activos · puedes limpiarlos con un toque.":"explore.activeFilters","Los resultados públicos se actualizan automáticamente.":"explore.autoUpdate","Sin resultados":"explore.noResults","No hemos encontrado perfiles públicos activos que mostrar.":"explore.noPeople","Todavía no hay equipos públicos que mostrar.":"explore.noTeams","No se ha podido actualizar el guardado.":"explore.saveError",
  "Notificaciones":"notifications.title","Marcar todas como leídas":"notifications.markAllRead","Nueva conversación":"chat.newConversation","Conversaciones":"chat.conversations","Buscar personas…":"chat.searchPeople","Selecciona una conversación":"chat.selectConversation","Tus mensajes aparecen aquí.":"chat.messagesHere","Escribe un mensaje…":"chat.writeMessage","Tu comunidad, aquí.":"chat.communityHere","Nuevo viaje":"travel.newTrip","Crear viaje":"travel.createTrip"
};
function applyLegacyTextTranslations(root){const walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);const legacy=window.curruscosTranslations?.legacy||{};nodes.forEach(node=>{if(!node.parentElement)return;const original=node.nodeValue.trim();if(!original)return;const key=LEGACY_TEXT_KEYS[original];const translated=key?t(key):legacy[original];if(!translated||translated===original)return;const leading=(node.nodeValue.match(/^\s*/) || [""])[0];const trailing=(node.nodeValue.match(/\s*$/) || [""])[0];node.nodeValue=leading+translated+trailing;});}
function applyAttributeTranslations(root){const scope=root||document;scope.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.setAttribute("placeholder",t(el.dataset.i18nPlaceholder)));scope.querySelectorAll("[data-i18n-title]").forEach(el=>el.setAttribute("title",t(el.dataset.i18nTitle)));scope.querySelectorAll("[data-i18n-aria-label]").forEach(el=>el.setAttribute("aria-label",t(el.dataset.i18nAriaLabel)));scope.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));}
let i18nObserver=null;
function languageLabel(){const labels={es:"Idioma",en:"Language",fr:"Langue",de:"Sprache",it:"Lingua",pt:"Idioma",zh:"语言",ar:"اللغة"};return labels[getLanguage()]||"Language";}
function installI18nObserver(){if(i18nObserver||!document.body)return;i18nObserver=new MutationObserver(mutations=>{let target=null;for(const mutation of mutations){if(mutation.type==="childList"){target=mutation.target;break;}if(mutation.type==="characterData"){target=mutation.target.parentElement;break;}}if(target)applyLegacyTextTranslations(target);});i18nObserver.observe(document.body,{subtree:true,childList:true,characterData:true});}
function installLanguageSelector(){if(document.querySelector(".i18n-control"))return;const header=document.querySelector(".navbar,.landing-header");if(!header)return;const control=document.createElement("div");control.className="i18n-control";const select=document.createElement("select");select.className="i18n-select";select.setAttribute("aria-label",languageLabel());Object.entries(I18N_SUPPORTED_LANGUAGES).forEach(([code,info])=>{const option=document.createElement("option");option.value=code;option.textContent=info.native;select.appendChild(option);});select.value=getLanguage();select.addEventListener("change",()=>{localStorage.setItem(I18N_STORAGE_KEY,normalizeLanguage(select.value)||I18N_DEFAULT_LANGUAGE);window.location.reload();});control.appendChild(select);const menuButton=header.querySelector("#menuButton");const landingNav=header.querySelector(".landing-nav");if(landingNav)landingNav.prepend(control);else if(menuButton)header.insertBefore(control,menuButton);else header.appendChild(control);}
async function applyI18n(root){const language=getLanguage();window.curruscosTranslations=await loadLocale(language);document.documentElement.lang=language;document.documentElement.dir=I18N_SUPPORTED_LANGUAGES[language]?.dir||"ltr";document.documentElement.dataset.language=language;applyAttributeTranslations(root||document);applyLegacyTextTranslations(root||document);const title=document.querySelector("title");if(title){const key=LEGACY_TEXT_KEYS[title.textContent.trim()];if(key)title.textContent=t(key);}document.querySelectorAll("meta[name=description][data-i18n]").forEach(meta=>meta.setAttribute("content",t(meta.dataset.i18n)));installLanguageSelector();installI18nObserver();window.dispatchEvent(new CustomEvent("curruscos:language-changed",{detail:{language}}));}
window.curruscosI18n={supported:I18N_SUPPORTED_LANGUAGES,getLanguage,setLanguage(language){const normalized=normalizeLanguage(language);if(!normalized)return false;localStorage.setItem(I18N_STORAGE_KEY,normalized);window.location.reload();return true;},t,date:localeDate,number:localeNumber,currency:localeCurrency,ready:null};
window.curruscosI18n.ready=new Promise(resolve=>{const start=()=>applyI18n(document).then(()=>resolve(window.curruscosI18n)).catch(()=>resolve(window.curruscosI18n));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();});
