-- Avoid overlapping SELECT policies and keep management policies scoped to their write actions.
-- Access semantics remain unchanged.

 drop policy "Event creator or group admin manages matches" on public.event_matches;
 create policy "Event creator or group admin manages matches" on public.event_matches for insert to authenticated with check (exists (select 1 from public.events e where e.id=event_matches.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin updates matches" on public.event_matches for update to authenticated using (exists (select 1 from public.events e where e.id=event_matches.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin'))))) with check (exists (select 1 from public.events e where e.id=event_matches.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin deletes matches" on public.event_matches for delete to authenticated using (exists (select 1 from public.events e where e.id=event_matches.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));

 drop policy "Event creator or group admin manages team members" on public.event_team_members;
 create policy "Event creator or group admin manages team members" on public.event_team_members for insert to authenticated with check (exists (select 1 from public.event_teams et join public.events e on e.id=et.event_id where et.id=event_team_members.team_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin updates team members" on public.event_team_members for update to authenticated using (exists (select 1 from public.event_teams et join public.events e on e.id=et.event_id where et.id=event_team_members.team_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin'))))) with check (exists (select 1 from public.event_teams et join public.events e on e.id=et.event_id where et.id=event_team_members.team_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin deletes team members" on public.event_team_members for delete to authenticated using (exists (select 1 from public.event_teams et join public.events e on e.id=et.event_id where et.id=event_team_members.team_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));

 drop policy "Event creator or group admin manages teams" on public.event_teams;
 create policy "Event creator or group admin manages teams" on public.event_teams for insert to authenticated with check (exists (select 1 from public.events e where e.id=event_teams.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin updates teams" on public.event_teams for update to authenticated using (exists (select 1 from public.events e where e.id=event_teams.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin'))))) with check (exists (select 1 from public.events e where e.id=event_teams.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));
 create policy "Event creator or group admin deletes teams" on public.event_teams for delete to authenticated using (exists (select 1 from public.events e where e.id=event_teams.event_id and (e.created_by=(select auth.uid()) or exists (select 1 from public.group_members gm where gm.group_id=e.group_id and gm.user_id=(select auth.uid()) and gm.role in ('owner','admin')))));

 alter policy "Anyone can discover public events" on public.events using ((visibility='public' and status in ('published','finished')) or (group_id is not null and exists (select 1 from public.group_members gm where gm.group_id=events.group_id and gm.user_id=(select auth.uid()))) or (visibility='unlisted' and created_by=(select auth.uid())));
 drop policy "Users can view their group events" on public.events;
 drop policy "Users can view unlisted events they created" on public.events;
